### 1. Login
POST http://localhost:8080/query
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRyaWZ0d2F5dGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUzMTU0MjA3LCJleHAiOjE3NTMxNTc4MDd9.x9xcuGGtSpCQ5qigU7u4WEg8Y0Bv6KfsSyza_39BWfc

{
    "data": [
        {
            "fieldIndex": "1",
            "label": "Relevant job experience"
        },
        {
            "fieldIndex": "2",
            "label": "Why should we hire you?"
        }
    ]
}
