### 1. Login
POST http://localhost:8080/query
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhZGlydXN1Ym9taUBnbWFpbC5jb20iLCJpYXQiOjE3NTMxNDYzMjksImV4cCI6MTc1MzE0OTkyOX0.P3LvXe_02iA-FHANj4Jl8PJ6hd1vKILK4lRlwQdZHjY

{
    "data": [
        {
            "formIndex": "1",
            "labels": ["Relevant job experience", "Why should we hire you?"]
        }        
    ]
}
